
export class VanBan  {
    constructor(
        public id?: number,
        public hososo?: number,
        public hosoid?: number,
        public vanbanso?: string,
        public stttronghs?: number,
        public loaivanban?: string,
        public noidung?: string,
        public soto?: number,
        public trangthai?: string,
        public mucdotincay?: string,
        public tinhtrang?: string,
        public thoigianbatdau?: Date,
        public thoigianketthuc?: Date,
        public thoihanbaoquan?: Number,
        public ghichu?: string,
    ) {
    }
}

export const vanbans : VanBan[] = [
    {
        id: 1,
        hososo: 712,
        hosoid: 1,
        vanbanso: "02",
        stttronghs: 21,
        loaivanban: "Văn bản hành chính",
        noidung: "Văn bản hành chính",
        soto: 100,
        mucdotincay: "Bản chính",
        tinhtrang: "Cũ",
        ghichu: "string", 
      },
      {
        id: 2,
        hososo: 715,
        hosoid: 2,
        vanbanso: "02",
        stttronghs: 21,
        loaivanban: "Văn bản hành pháp",
        noidung: "Văn bản hành pháp",
        soto: 100,
        mucdotincay: "Bản sao",
        tinhtrang: "Mới",
        ghichu: "string",
      },
      {
        id: 3,
        hososo: 812,
        hosoid: 3,
        vanbanso: "02",
        stttronghs: 21,
        loaivanban: "Văn bản pháp lý",
        noidung: "Văn bản pháp lý",
        soto: 100,
        mucdotincay: "Bản photo",
        tinhtrang: "Mới",
        ghichu: "string",
      },
      {
        id: 4,
        hososo: 613,
        hosoid: 1,
        vanbanso: "02",
        stttronghs: 21,
        loaivanban: "Văn bản kiểm kê",
        noidung: "Văn bản kiểm kê",
        soto: 100,
        mucdotincay: "Bản chính",
        tinhtrang: "Cũ",
        ghichu: "string",
      },
      {
        id: 5,
        hososo: 513,
        hosoid: 4,
        vanbanso: "02",
        stttronghs: 21,
        loaivanban: "Văn bản thường",
        noidung: "Văn bản thường",
        soto: 100,
        mucdotincay: "Bản sao",
        tinhtrang: "Cũ",
        ghichu: "string",
      }
]